### ISSUE TITLE
Images by Tag

### ISSUE THREAD

**Issue by scottspeidel** [AppFolioOnboarding/perkins_eidolon#11]
#### As a user I want to view all images associated with a tag.

Acceptance criteria:
- [x] When I click on a tag, I see a filtered list of only the images that have
  the tag I clicked on.
- [x] The tag name (not its ID) is used to perform the filtering.

Discussion topics:
- [x] Where should we implement this functionality?
- [x] What happens if a user tries to manually filter by a nonexistent tag?

Dependencies:
- Image Tags

**Comment by erikperkins** [comment]
Pull request here https://github.com/AppFolioOnboarding/perkins_eidolon/pull/46
