### ISSUE TITLE
Tag Index

### ISSUE THREAD

**Issue by scottspeidel** [AppFolioOnboarding/perkins_eidolon#12]
#### As a user I want to see a list of tags and the number of images associated with each.

Acceptance criteria:
- [x] There is a link in the application that takes me to a list of all tags.
- [x] The tag list is sorted by frequency with the most common first.
- [x] Each tag name is a link to the image list filtered by that tag.

Dependencies:
- Images by Tag

**Comment by bboe** [comment]
Is there a PR associated with this issue?

**Comment by erikperkins** [comment]
:shipit:
