### ISSUE TITLE
ES6 Configuration

### ISSUE THREAD

**Issue by scottspeidel** [AppFolioOnboarding/perkins_eidolon#15]
#### As a developer I want to use the latest and greatest javascript features, including ES6 modules, in my application.

Acceptance criteria:
- [ ] I can develop using ES6 modules and they will be transpiled to supported
  syntax.
- [ ] I have configured my production setup to support this transpilation.
- [x] A "hello world" ES6 module has been added to the application.
- [ ] I know how to include javascript modules only on a given page, as
  demonstrated by only including this "hello world" module on the images index.

Discussion topics:
- [ ] What are the benefits of using ES6 modules?
- [ ] What is transpilation and why is it awesome?

Reference material:
- https://docs.google.com/a/appfolio.com/document/d/1Z9INywyV84fDyRTO0ZAOYivQWmxpXspN2o2vdKK3vBA/edit?usp=sharing

Further reading:
- List of ES6 features: http://git.io/es6features

Dependencies:
- Image Index

**Comment by bboe** [comment]
@rmacklin can this issue be closed?

**Comment by rmacklin** [comment]
In https://github.com/AppFolioOnboarding/perkins_eidolon/pull/40#issuecomment-193491626, I said:
> you should make sure it works on your staging application (and your production application if you then promote staging to production).
If that's been verified, it can be closed.

**Comment by bboe** [comment]
@erikperkins can you do that verification and if it works close the issue?

**Comment by erikperkins** [comment]
Verified that the application works in staging after running a migration.
