### ISSUE TITLE
Save Image Link

### ISSUE THREAD

**Issue by scottspeidel** [AppFolioOnboarding/perkins_eidolon#3]
#### As a user I want to save a link to an image.

Acceptance criteria:
- [x] The link is entered through a form.
- [x] After the form is saved, the link is persisted in the database.

Dependencies:
- Deployment Environment

**Comment by bboe** [comment]
I've added some comments to #21 which has been merged. This issue should remain open until those comments have been addressed. Below is a summary:

- [ ] Add confirmation “flash” message when actions succeed (image created, image deleted, etc)
- [ ] Use unprocessable entity status codes for failed actions
- [ ] Use a verb-phrase for validation error messages
- [ ] Update `.gitignore`
- [ ] Remove `db/development.sqlite3` from git
- [ ] Remove `db/test.sqlite3` from git
- [ ] Update ‘image ‘ test to be more descriptive
- [ ] Move `assert_response` lines outside of `assert_difference` blocks.
- [ ] Split `’image URL is valid` test into three separate tests

**Comment by rmacklin** [comment]
I also added a few comments to #21:

https://github.com/AppFolioOnboarding/perkins_eidolon/pull/21#discussion_r54497086
https://github.com/AppFolioOnboarding/perkins_eidolon/pull/21#discussion_r54497252
https://github.com/AppFolioOnboarding/perkins_eidolon/pull/21#discussion_r54497403

**Comment by erikperkins** [comment]
Reviewed in person with bboe.
