### ISSUE TITLE
Image Index

### ISSUE THREAD

**Issue by scottspeidel** [AppFolioOnboarding/perkins_eidolon#4]
#### As a user I want the homepage to display all saved images.

Acceptance criteria:
- [x] New images that are added show up on the homepage.
- [x] These images are persisted if the browser is closed or even if the
  server is restarted.
- [x] Images are not displayed wider than 400px.

Dependencies:
- Save Image Link

**Comment by bboe** [comment]
I added some comments to the merged pull request #22. This issue can be closed once those have been resolved and @aaronpanch signs off as well.

**Comment by rmacklin** [comment]
I added some comments to #22 as well.
